// Generates the marketing video's backing track with the ElevenLabs Music API and writes
// it to public/music/backing.mp3. Cached by a hash of (prompt, durationMs, model)
// so re-renders don't re-bill the API; the sidecar meta also lets teammates and
// CI render without a key as long as the cached mp3 exists.

import { createHash } from "node:crypto";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { FPS, TOTAL_DURATION } from "../src/config/timing.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");
const musicDir = resolve(here, "../public/music");
const mp3Path = resolve(musicDir, "backing.mp3");
const metaPath = resolve(musicDir, "backing.meta.json");
const generatedFile = resolve(here, "../src/generated/music.ts");

const PROMPT = [
  "Modern minimal tech product launch underscore. Very gentle muted synth",
  "bass, barely-there steady eighth-note pulse at ~95 BPM, warm pad",
  "underneath, clean and confident. No vocals, no lead melody, no heavy",
  "sub, no kick drum, no busy percussion. Think Linear, Vercel, Apple",
  "software reveal: restrained, airy, with quiet momentum. Smooth fade-in",
  "and tail.",
].join(" ");

const MODEL_ID = "music_v1";
const OUTPUT_FORMAT = "mp3_44100_128";

// The track needs to outlast the visuals by a beat so the tail doesn't get
// cut mid-pad. Round up to the nearest 250ms over the composition length.
const compositionMs = (TOTAL_DURATION / FPS) * 1000;
const DURATION_MS = Math.ceil((compositionMs + 250) / 250) * 250;

type Meta = {
  promptHash: string;
  durationMs: number;
  model: string;
};

function hash(input: string): string {
  return createHash("sha256").update(input).digest("hex").slice(0, 16);
}

async function exists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

async function readMeta(): Promise<Meta | null> {
  if (!(await exists(metaPath))) return null;
  try {
    return JSON.parse(await readFile(metaPath, "utf8")) as Meta;
  } catch {
    return null;
  }
}

async function callElevenLabs(
  apiKey: string,
  promptHash: string,
): Promise<void> {
  const url = new URL("https://api.elevenlabs.io/v1/music");
  url.searchParams.set("output_format", OUTPUT_FORMAT);

  const res = await fetch(url, {
    method: "POST",
    headers: {
      "xi-api-key": apiKey,
      "Content-Type": "application/json",
      Accept: "audio/mpeg",
    },
    body: JSON.stringify({
      prompt: PROMPT,
      music_length_ms: DURATION_MS,
      model_id: MODEL_ID,
      force_instrumental: true,
    }),
  });

  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(
      `ElevenLabs Music API ${res.status} ${res.statusText}: ${detail.slice(0, 500)}`,
    );
  }

  const buf = new Uint8Array(await res.arrayBuffer());
  await mkdir(musicDir, { recursive: true });
  await writeFile(mp3Path, buf);
  const meta: Meta = {
    promptHash,
    durationMs: DURATION_MS,
    model: MODEL_ID,
  };
  await writeFile(metaPath, `${JSON.stringify(meta, null, 2)}\n`);
}

function emitGenerated(): string {
  return [
    "// AUTO-GENERATED by scripts/generate-music.ts. Do not edit.",
    "// Re-run with `pnpm --filter @web-kits/marketing music`.",
    "",
    'import { staticFile } from "remotion";',
    "",
    "export const backingTrack = {",
    `  src: staticFile("music/backing.mp3"),`,
    `  durationInSeconds: ${(DURATION_MS / 1000).toFixed(3)},`,
    "} as const;",
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  // Always emit the generated TS file — it's a static reference to the
  // public path and lets `tsc --noEmit` pass even before the mp3 exists.
  await mkdir(musicDir, { recursive: true });
  await writeFile(generatedFile, emitGenerated());
  console.log(`music: wrote ${relative(repoRoot, generatedFile)}`);

  const promptHash = hash(`${PROMPT}::${MODEL_ID}::${OUTPUT_FORMAT}`);
  const meta = await readMeta();
  const cacheHit =
    meta !== null &&
    meta.promptHash === promptHash &&
    meta.durationMs === DURATION_MS &&
    meta.model === MODEL_ID &&
    (await exists(mp3Path));

  if (cacheHit) {
    console.log(
      `music: cache hit (${(DURATION_MS / 1000).toFixed(2)}s) — skipping API call`,
    );
    return;
  }

  const apiKey = process.env.ELEVENLABS_API_KEY;
  if (!apiKey) {
    if (await exists(mp3Path)) {
      console.warn(
        "music: ELEVENLABS_API_KEY not set and cache is stale; using existing backing.mp3",
      );
      return;
    }
    console.warn(
      "music: ELEVENLABS_API_KEY is not set and no cached backing.mp3 exists. " +
        "Set ELEVENLABS_API_KEY and re-run `pnpm --filter marketing music` to generate one. " +
        "Renders will play without a backing track until then.",
    );
    return;
  }

  console.log(
    `music: generating ${(DURATION_MS / 1000).toFixed(2)}s track via ElevenLabs Music API…`,
  );
  await callElevenLabs(apiKey, promptHash);
  console.log(`music: wrote ${relative(repoRoot, mp3Path)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
