import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { getInstalledPatches } from "../src/commands/utils.js";

describe("getInstalledPatches", () => {
  let tempDir: string;
  let originalCwd: string;

  beforeEach(() => {
    originalCwd = process.cwd();
    tempDir = join(
      tmpdir(),
      `audio-test-${Date.now()}-${Math.random().toString(36).slice(2)}`,
    );
    mkdirSync(tempDir, { recursive: true });
    process.chdir(tempDir);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    rmSync(tempDir, { recursive: true, force: true });
  });

  it("returns empty array when patches directory does not exist", async () => {
    const patches = await getInstalledPatches();
    expect(patches).toEqual([]);
  });

  it("returns patches from .ts files in the output directory", async () => {
    const outDir = join(tempDir, ".web-kits");
    mkdirSync(outDir, { recursive: true });

    const moduleContent = [
      "// test-patch — generated by @web-kits/audio (do not edit)",
      "// patch: Test Patch",
      'import type { SoundDefinition, SoundPatch } from "@web-kits/audio";',
      "",
      'export const click: SoundDefinition = {"source":{"type":"sine"}};',
      "",
      'export const pop: SoundDefinition = {"source":{"type":"sine"}};',
      "",
      "export const _patch: SoundPatch = {",
      '  ...{"name":"Test Patch"},',
      "  sounds: { click, pop },",
      "};",
      "",
    ].join("\n");

    writeFileSync(join(outDir, "test-patch.ts"), moduleContent);

    const patches = await getInstalledPatches();
    expect(patches).toHaveLength(1);
    expect(patches[0].name).toBe("Test Patch");
    expect(patches[0].soundCount).toBe(2);
    expect(patches[0].file).toBe("test-patch.ts");
  });

  it("skips index.ts", async () => {
    const outDir = join(tempDir, ".web-kits");
    mkdirSync(outDir, { recursive: true });

    writeFileSync(
      join(outDir, "index.ts"),
      'export * as core from "./core";\n',
    );
    writeFileSync(
      join(outDir, "core.ts"),
      [
        "// patch: Core",
        'import type { SoundDefinition, SoundPatch } from "@web-kits/audio";',
        'export const click: SoundDefinition = {"source":{"type":"sine"}};',
        "export const _patch: SoundPatch = {",
        '  ...{"name":"Core"},',
        "  sounds: { click },",
        "};",
      ].join("\n"),
    );

    const patches = await getInstalledPatches();
    expect(patches).toHaveLength(1);
    expect(patches[0].name).toBe("Core");
  });

  it("skips non-.ts files", async () => {
    const outDir = join(tempDir, ".web-kits");
    mkdirSync(outDir, { recursive: true });

    writeFileSync(join(outDir, "readme.md"), "# hello");

    const patches = await getInstalledPatches();
    expect(patches).toEqual([]);
  });
});
